# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from danube.proto import DanubeApi_pb2 as DanubeApi__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in DanubeApi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProducerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProducer = channel.unary_unary(
                '/danube.ProducerService/CreateProducer',
                request_serializer=DanubeApi__pb2.ProducerRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.ProducerResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/danube.ProducerService/SendMessage',
                request_serializer=DanubeApi__pb2.StreamMessage.SerializeToString,
                response_deserializer=DanubeApi__pb2.MessageResponse.FromString,
                _registered_method=True)


class ProducerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProducer(self, request, context):
        """Creates a new Producer on a topic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Sends a message from the Producer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProducerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProducer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProducer,
                    request_deserializer=DanubeApi__pb2.ProducerRequest.FromString,
                    response_serializer=DanubeApi__pb2.ProducerResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=DanubeApi__pb2.StreamMessage.FromString,
                    response_serializer=DanubeApi__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'danube.ProducerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('danube.ProducerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProducerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProducer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.ProducerService/CreateProducer',
            DanubeApi__pb2.ProducerRequest.SerializeToString,
            DanubeApi__pb2.ProducerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.ProducerService/SendMessage',
            DanubeApi__pb2.StreamMessage.SerializeToString,
            DanubeApi__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConsumerServiceStub(object):
    """============================================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_unary(
                '/danube.ConsumerService/Subscribe',
                request_serializer=DanubeApi__pb2.ConsumerRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.ConsumerResponse.FromString,
                _registered_method=True)
        self.ReceiveMessages = channel.unary_stream(
                '/danube.ConsumerService/ReceiveMessages',
                request_serializer=DanubeApi__pb2.ReceiveRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.StreamMessage.FromString,
                _registered_method=True)
        self.Ack = channel.unary_unary(
                '/danube.ConsumerService/Ack',
                request_serializer=DanubeApi__pb2.AckRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.AckResponse.FromString,
                _registered_method=True)


class ConsumerServiceServicer(object):
    """============================================================================================

    """

    def Subscribe(self, request, context):
        """Creates a new Subscriber
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """Streaming messages to the Subscriber
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ack(self, request, context):
        """Acknowledges receipt of a message from the Consumer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=DanubeApi__pb2.ConsumerRequest.FromString,
                    response_serializer=DanubeApi__pb2.ConsumerResponse.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=DanubeApi__pb2.ReceiveRequest.FromString,
                    response_serializer=DanubeApi__pb2.StreamMessage.SerializeToString,
            ),
            'Ack': grpc.unary_unary_rpc_method_handler(
                    servicer.Ack,
                    request_deserializer=DanubeApi__pb2.AckRequest.FromString,
                    response_serializer=DanubeApi__pb2.AckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'danube.ConsumerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('danube.ConsumerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsumerService(object):
    """============================================================================================

    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.ConsumerService/Subscribe',
            DanubeApi__pb2.ConsumerRequest.SerializeToString,
            DanubeApi__pb2.ConsumerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/danube.ConsumerService/ReceiveMessages',
            DanubeApi__pb2.ReceiveRequest.SerializeToString,
            DanubeApi__pb2.StreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.ConsumerService/Ack',
            DanubeApi__pb2.AckRequest.SerializeToString,
            DanubeApi__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DiscoveryStub(object):
    """============================================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TopicLookup = channel.unary_unary(
                '/danube.Discovery/TopicLookup',
                request_serializer=DanubeApi__pb2.TopicLookupRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.TopicLookupResponse.FromString,
                _registered_method=True)
        self.TopicPartitions = channel.unary_unary(
                '/danube.Discovery/TopicPartitions',
                request_serializer=DanubeApi__pb2.TopicLookupRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.TopicPartitionsResponse.FromString,
                _registered_method=True)


class DiscoveryServicer(object):
    """============================================================================================

    """

    def TopicLookup(self, request, context):
        """Query the Danube broker for information about a specific topic.
        returns metadata about the topic, including the broker(s) responsible for it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopicPartitions(self, request, context):
        """Query the Danube broker for information about topic partitions.
        returns an array with the topic partitions names
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TopicLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.TopicLookup,
                    request_deserializer=DanubeApi__pb2.TopicLookupRequest.FromString,
                    response_serializer=DanubeApi__pb2.TopicLookupResponse.SerializeToString,
            ),
            'TopicPartitions': grpc.unary_unary_rpc_method_handler(
                    servicer.TopicPartitions,
                    request_deserializer=DanubeApi__pb2.TopicLookupRequest.FromString,
                    response_serializer=DanubeApi__pb2.TopicPartitionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'danube.Discovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('danube.Discovery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Discovery(object):
    """============================================================================================

    """

    @staticmethod
    def TopicLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.Discovery/TopicLookup',
            DanubeApi__pb2.TopicLookupRequest.SerializeToString,
            DanubeApi__pb2.TopicLookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TopicPartitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.Discovery/TopicPartitions',
            DanubeApi__pb2.TopicLookupRequest.SerializeToString,
            DanubeApi__pb2.TopicPartitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthCheckStub(object):
    """============================================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/danube.HealthCheck/HealthCheck',
                request_serializer=DanubeApi__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthCheckServicer(object):
    """============================================================================================

    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=DanubeApi__pb2.HealthCheckRequest.FromString,
                    response_serializer=DanubeApi__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'danube.HealthCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('danube.HealthCheck', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthCheck(object):
    """============================================================================================

    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.HealthCheck/HealthCheck',
            DanubeApi__pb2.HealthCheckRequest.SerializeToString,
            DanubeApi__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthServiceStub(object):
    """============================================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/danube.AuthService/Authenticate',
                request_serializer=DanubeApi__pb2.AuthRequest.SerializeToString,
                response_deserializer=DanubeApi__pb2.AuthResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """============================================================================================

    """

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=DanubeApi__pb2.AuthRequest.FromString,
                    response_serializer=DanubeApi__pb2.AuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'danube.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('danube.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """============================================================================================

    """

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube.AuthService/Authenticate',
            DanubeApi__pb2.AuthRequest.SerializeToString,
            DanubeApi__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
