# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from danube.proto import SchemaRegistry_pb2 as SchemaRegistry__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in SchemaRegistry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchemaRegistryStub(object):
    """Schema Registry Service for managing schemas across the Danube cluster
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSchema = channel.unary_unary(
                '/danube_schema.SchemaRegistry/RegisterSchema',
                request_serializer=SchemaRegistry__pb2.RegisterSchemaRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.RegisterSchemaResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/danube_schema.SchemaRegistry/GetSchema',
                request_serializer=SchemaRegistry__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.GetLatestSchema = channel.unary_unary(
                '/danube_schema.SchemaRegistry/GetLatestSchema',
                request_serializer=SchemaRegistry__pb2.GetLatestSchemaRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_unary(
                '/danube_schema.SchemaRegistry/ListVersions',
                request_serializer=SchemaRegistry__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.CheckCompatibility = channel.unary_unary(
                '/danube_schema.SchemaRegistry/CheckCompatibility',
                request_serializer=SchemaRegistry__pb2.CheckCompatibilityRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.CheckCompatibilityResponse.FromString,
                _registered_method=True)
        self.DeleteSchemaVersion = channel.unary_unary(
                '/danube_schema.SchemaRegistry/DeleteSchemaVersion',
                request_serializer=SchemaRegistry__pb2.DeleteSchemaVersionRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.DeleteSchemaVersionResponse.FromString,
                _registered_method=True)
        self.SetCompatibilityMode = channel.unary_unary(
                '/danube_schema.SchemaRegistry/SetCompatibilityMode',
                request_serializer=SchemaRegistry__pb2.SetCompatibilityModeRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.SetCompatibilityModeResponse.FromString,
                _registered_method=True)
        self.ConfigureTopicSchema = channel.unary_unary(
                '/danube_schema.SchemaRegistry/ConfigureTopicSchema',
                request_serializer=SchemaRegistry__pb2.ConfigureTopicSchemaRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.ConfigureTopicSchemaResponse.FromString,
                _registered_method=True)
        self.UpdateTopicValidationPolicy = channel.unary_unary(
                '/danube_schema.SchemaRegistry/UpdateTopicValidationPolicy',
                request_serializer=SchemaRegistry__pb2.UpdateTopicValidationPolicyRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.UpdateTopicValidationPolicyResponse.FromString,
                _registered_method=True)
        self.GetTopicSchemaConfig = channel.unary_unary(
                '/danube_schema.SchemaRegistry/GetTopicSchemaConfig',
                request_serializer=SchemaRegistry__pb2.GetTopicSchemaConfigRequest.SerializeToString,
                response_deserializer=SchemaRegistry__pb2.GetTopicSchemaConfigResponse.FromString,
                _registered_method=True)


class SchemaRegistryServicer(object):
    """Schema Registry Service for managing schemas across the Danube cluster
    """

    def RegisterSchema(self, request, context):
        """Register a new schema or get existing schema ID if identical schema exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Get a specific schema by ID and optional version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestSchema(self, request, context):
        """Get the latest version of a schema for a subject
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """List all versions for a subject
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCompatibility(self, request, context):
        """Check if a new schema is compatible with existing versions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchemaVersion(self, request, context):
        """Delete a specific schema version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCompatibilityMode(self, request, context):
        """Set or update compatibility mode for a subject
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureTopicSchema(self, request, context):
        """===== Admin-only operations for topic schema configuration =====

        Configure schema settings for a topic (admin-only)
        Allows admin to assign/change schema subject and validation settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTopicValidationPolicy(self, request, context):
        """Update validation policy for a topic (admin-only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopicSchemaConfig(self, request, context):
        """Get current schema configuration for a topic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchemaRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSchema,
                    request_deserializer=SchemaRegistry__pb2.RegisterSchemaRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.RegisterSchemaResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=SchemaRegistry__pb2.GetSchemaRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.GetSchemaResponse.SerializeToString,
            ),
            'GetLatestSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestSchema,
                    request_deserializer=SchemaRegistry__pb2.GetLatestSchemaRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.GetSchemaResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=SchemaRegistry__pb2.ListVersionsRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.ListVersionsResponse.SerializeToString,
            ),
            'CheckCompatibility': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCompatibility,
                    request_deserializer=SchemaRegistry__pb2.CheckCompatibilityRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.CheckCompatibilityResponse.SerializeToString,
            ),
            'DeleteSchemaVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchemaVersion,
                    request_deserializer=SchemaRegistry__pb2.DeleteSchemaVersionRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.DeleteSchemaVersionResponse.SerializeToString,
            ),
            'SetCompatibilityMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCompatibilityMode,
                    request_deserializer=SchemaRegistry__pb2.SetCompatibilityModeRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.SetCompatibilityModeResponse.SerializeToString,
            ),
            'ConfigureTopicSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureTopicSchema,
                    request_deserializer=SchemaRegistry__pb2.ConfigureTopicSchemaRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.ConfigureTopicSchemaResponse.SerializeToString,
            ),
            'UpdateTopicValidationPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTopicValidationPolicy,
                    request_deserializer=SchemaRegistry__pb2.UpdateTopicValidationPolicyRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.UpdateTopicValidationPolicyResponse.SerializeToString,
            ),
            'GetTopicSchemaConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopicSchemaConfig,
                    request_deserializer=SchemaRegistry__pb2.GetTopicSchemaConfigRequest.FromString,
                    response_serializer=SchemaRegistry__pb2.GetTopicSchemaConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'danube_schema.SchemaRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('danube_schema.SchemaRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchemaRegistry(object):
    """Schema Registry Service for managing schemas across the Danube cluster
    """

    @staticmethod
    def RegisterSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/RegisterSchema',
            SchemaRegistry__pb2.RegisterSchemaRequest.SerializeToString,
            SchemaRegistry__pb2.RegisterSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/GetSchema',
            SchemaRegistry__pb2.GetSchemaRequest.SerializeToString,
            SchemaRegistry__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/GetLatestSchema',
            SchemaRegistry__pb2.GetLatestSchemaRequest.SerializeToString,
            SchemaRegistry__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/ListVersions',
            SchemaRegistry__pb2.ListVersionsRequest.SerializeToString,
            SchemaRegistry__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckCompatibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/CheckCompatibility',
            SchemaRegistry__pb2.CheckCompatibilityRequest.SerializeToString,
            SchemaRegistry__pb2.CheckCompatibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchemaVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/DeleteSchemaVersion',
            SchemaRegistry__pb2.DeleteSchemaVersionRequest.SerializeToString,
            SchemaRegistry__pb2.DeleteSchemaVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCompatibilityMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/SetCompatibilityMode',
            SchemaRegistry__pb2.SetCompatibilityModeRequest.SerializeToString,
            SchemaRegistry__pb2.SetCompatibilityModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureTopicSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/ConfigureTopicSchema',
            SchemaRegistry__pb2.ConfigureTopicSchemaRequest.SerializeToString,
            SchemaRegistry__pb2.ConfigureTopicSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTopicValidationPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/UpdateTopicValidationPolicy',
            SchemaRegistry__pb2.UpdateTopicValidationPolicyRequest.SerializeToString,
            SchemaRegistry__pb2.UpdateTopicValidationPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopicSchemaConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/danube_schema.SchemaRegistry/GetTopicSchemaConfig',
            SchemaRegistry__pb2.GetTopicSchemaConfigRequest.SerializeToString,
            SchemaRegistry__pb2.GetTopicSchemaConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
